export { default as AdminBadge } from './AdminBadge.vue';
export { default as CategoryBadge } from './CategoryBadge.vue';
export { default as DifficultyBadge } from './DifficultyBadge.vue';
export { default as QuizzesCountBadge } from './QuizzesCountBadge.vue';
export { default as ThemeBadge } from './ThemeBadge.vue';
export { default as TwoFactorConfirmedBadge } from './TwoFactorConfirmedBadge.vue';
export { default as UnavailableBadge } from './UnavailableBadge.vue';
export { default as UserRoleBadge } from './UserRoleBadge.vue';
export { default as VerifiedEmailBadge } from './VerifiedEmailBadge.vue';
